apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-bekk
spec:
  template:
    spec:
      containers:
        - name: application
          env:
            - name: SITE__GREETING
              value: "Bekk"
            - name: SITE__FROM
              value: "Azure Sweden Central"
