apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-bekk
  labels:
    app: hello-world-bekk
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world-bekk
  template:
    metadata:
      name: hello-world-bekk
      labels:
        app: hello-world-bekk
    spec:
      containers:
        - name: application
          image: ghcr.io/andersro93/bekk-hello-world:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 11337
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - NET_RAW
                - ALL
        - name: cloudflared
          image: cloudflare/cloudflared:latest
          imagePullPolicy: Always
          args: 
            - tunnel
            - run
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  key: token
                  name: cloudflared-secret
            - name: TUNNEL_POST_QUANTUM
              value: "true"
            - name: TUNNEL_ORIGIN_ENABLE_HTTP2
              value: "true"
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 11337
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - NET_RAW
                - ALL
      restartPolicy: Always
      